model: tf_efficientnet_b7_ns
pretrained: true
num_classes: 10
img_size: 600
batch_size: 4

# hflip: 0
# vflip: 0
# scale: [0.9, 1.0]  
# ratio: [1.0,1.0]
# color_jitter: 0

opt: momentum
lr:  1e-2
weight-decay: 1e-4

epochs: 90
sched: step
decay_epochs: 30
decay_rate: 0.1


cutmix: 1.0
reprob: 0.5
 
freeze-layer: 5


aa: corr-aug
#native-amp: True

#aa: corr-aug

#smoothing: 0.0
